name: primebot

on:
  schedule:
    - cron:  '55 * * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Next Prime
        run: go run main.go

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
